name: manifest
on:
  pull_request:
    branches: 
      - main
    paths:
      - "k8s/**"
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Azure login
        id: login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - run: az account set --subscription 2d590b4b-3a4b-4851-acf5-886dcb61d2f5
      - run: az aks get-credentials --resource-group k8 --name dev
      - run: kubectl apply -f  k8s -R

