name: manifest
on:
  pull_request:
    branches: 
      - main
    paths:
      - "k8s/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: az aks install-cli
      - run: az aks get-credentials --resource-group k8s --name dev
      - run: kubectl apply -f ./k8s
