name: manifest
on:
  pull_request:
    branches: 
      - main
    paths:
      - "k8s/**"
      
permissions:
      id-token: write
      contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - run: az account set --subscription 2d590b4b-3a4b-4851-acf5-886dcb61d2f5
      - run: az aks get-credentials --resource-group k8 --name dev
      - run: kubectl apply -f k8s
